PyLightServer/urls.py
from django.contrib import admin
from django.urls import include, path
import showTools
import manageTools

from PyLightCommon.Globals import *
from PyLightCommon.loghandler import setup_logging
import PyLightCommon.cmdHandler


urlpatterns = [
    path('', include('pwa.urls')),
    path('', include('showTools.urls')),
    path('showTools/', include(('showTools.urls','showTools'),namespace='showTools')),
    path('manageTools/', include(('manageTools.urls','manageTools'),namespace='manageTools')),
    path('cmdHandler/', include(('PyLightCommon.cmdHandler.urls','PyLightCommon.cmdHandler'),namespace='cmdHandler')),
    path('admin/', admin.site.urls),
    path(r'base_layout',showTools.views.base_layout),
    path(r'config_layout',manageTools.views.config_layout),
]

setup_logging()

manageTools/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ConnectedSystemsView.as_view(), name='index'),
    path('system/<int:connectedSystem_id>/', views.saveSystem, name='saveSystem'),
    path('io/<int:usedio_id>/', views.saveIO, name='saveIO'),
    path(r'config_layout',views.config_layout,name='config_layout'),
]

showTools/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ConnectedSystemsView.as_view(), name='home'),
    path(r'base_layout',views.base_layout,name='base_layout'),
    path('state/<int:usedio_id>/', views.saveState, name='saveState'),
]

manageTools/views.py
from django.views import generic
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

import logging

from PyLightCommon.pylightcommon.models import ConnectedSystem,UsedIO,IO,IOType
from PyLightCommon.cmdHandler.cmdHandler import sendCommand

logger = logging.getLogger(__name__)

class ConnectedSystemsView(generic.ListView):
    template_name='manageTools/index.html'
    context_object_name = 'connectedSystem_list'

    def get_queryset(self):
        logger.debug(f"Requesting query set: {ConnectedSystem.objects.order_by('-name')}")
        return ConnectedSystem.objects.order_by('-name')

def saveSystem(request, connectedSystem_id):
    connectedSystem = get_object_or_404(ConnectedSystem,pk=connectedSystem_id)
    sendCommand(connectedSystem.lastIP,
                commando='nameChange',
                id=connectedSystem_id,
                name=request.POST['system_name'])


    logger.info(f"Setting system name with id {connectedSystem_id} from {connectedSystem.name} to"
                f"{request.POST['system_name']}")

    return HttpResponseRedirect(reverse('manageTools:index'))

def saveIO(request, usedio_id):
    logger.debug("Adding new io")
    io = get_object_or_404(IO,pk=request.POST['io_selection'])
    ioType = get_object_or_404(IOType,pk=request.POST['io_type_selection'])

    logger.debug(f"Future io: {io}, type: {ioType}")

    usedIo = get_object_or_404(UsedIO,pk=usedio_id)

    sendCommand(usedIo.connectedSystem.lastIP,
                commando="addOut",
                name=request.POST['io_name'],
                pin=io,
                type=ioType)
    return HttpResponseRedirect(reverse('manageTools:index'))

def config_layout(request):
    template = 'manageTools/index.html'
    return render(request,template)

showTools/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect

import logging

from PyLightCommon.pylightcommon.models import ConnectedSystem,UsedIO
from PyLightCommon.cmdHandler.cmdHandler import sendCommand

logger = logging.getLogger(__name__)


class ConnectedSystemsView(generic.ListView):
    template_name = 'showTools/index.html'
    context_object_name = 'connectedSystem_list'

    def get_queryset(self):
        logger.debug(f"Requesting query set: {ConnectedSystem.objects.order_by('-name')}")
        return ConnectedSystem.objects.order_by('-name')


def base_layout(request):
    template = 'showTools/index.html'
    return render(request, template)


def saveState(request, usedio_id):
    logger.debug(f"Changing state of io {usedio_id}")
    usedIo = UsedIO.objects.get(pk=usedio_id)
    if 'io_switch' in request.POST:
        sendCommand(usedIo.connectedSystem.lastIP,
                    commando="changeOut",
                    usedIO_id=usedio_id,
                    active=True)
        logger.info(f"Setting {usedIo} to True")
    else:

        sendCommand(usedIo.connectedSystem.lastIP,
                    commando="changeOut",
                    usedIO_id=usedio_id,
                    active=False)
        logger.info(f"Setting {usedIo} to False")

    return HttpResponseRedirect(reverse('showTools:base_layout'))

manageTools/templates/manageTools/index.html
{% extends 'manageTools/loops.html' %}
{% load staticfiles %}

{% block ioName %}
    <label for="io_name:{{ usedio.id }}">IO Name</label>
    <input type="text" name ="io_name" id ="io_name:{{ usedio.id }}" value="{{ usedio.name }}">
{% endblock %}

{% block pinLoop %}
    <label for="io_selection{{ usedio.id }}">IO:</label>
    <select name="io_selection" id="io_selection{{ usedio.id }}" onchange="this.form.submit()">
        {% for io in usedio.pin.getAllObjects %}
            {% if io.ioNr != usedio.pin.ioNr %}
                <option value="{{ io.ioNr }}">{{ io.ioNr }}</option>
            {% endif %}
            {% if io.ioNr == usedio.pin.ioNr %}
                <option selected="selected" value="{{ io.ioNr }}">{{ io.ioNr }}</option>
            {% endif %}
        {% endfor %}
    </select>
{% endblock %}

{% block typeLoop %}
    <label for="io_type_selection{{ usedio.id }}">IO Typ:</label>
    <select name="io_type_selection" id="io_type_selection{{ usedio.id }}" onchange="this.form.submit()">
        {% for ioType in usedio.type.getAllObjects %}
            {% if ioType.id != usedio.type_id %}
                <option value="{{ ioType.id  }}">{{ ioType.id }}</option>
            {% endif %}
            {% if ioType.id == usedio.type_id %}
                <option selected="selected" value="{{ ioType.id  }}">{{ ioType.id }}</option>
            {% endif %}
        {% endfor %}
    </select>
{% endblock %}

manageTools/templates/manageTools/loops.html
{% extends 'initial.html' %}
{% load staticfiles %}

{% block systemForm %}
    <form action="{% url 'manageTools:saveSystem' connectedSystem.id %}" method="post">
        {%  csrf_token %}
            <strong><label for="{{ connectedSystem.id }}">Systemname:</label></strong>
            <input type="text" name="system_name" id={{ connectedSystem.id }} value="{{ connectedSystem.name }}">
        </br>
        <strong>IP: </strong>{{ connectedSystem.lastIP }}
        </br>
        <strong>Mac Adresse: </strong>{{ connectedSystem.lastMacAddress }}
        </br>
        <strong>Seriennummer: </strong>{{ connectedSystem.serialNumber }}
        </br>
        </br>
        <strong>ConnectedStatus: </strong>{{ connectedSystem.connected }}
        </br>
        </br>
        </br>

    </form>
{% endblock %}

{% block ioForm %}
    <form action="{% url 'manageTools:saveIO' usedio.id %}" method="post">
        {%  csrf_token %}

        {% block ioName %}
        {% endblock %}

        {% block pinLoop %}
        {% endblock %}

        {% block typeLoop %}
        {% endblock %}
    </form>
{% endblock %}

showTools/templates/showTools/index.html
{% extends 'initial.html' %}
{% load staticfiles %}

{% block systemForm %}

    <div class="Systems_overview">
        <h3><strong id="system_name:{{ connectedSystem_id }}">{{ connectedSystem.name }} </strong></h3>
    </div>
{% endblock %}

{% block ioForm %}
    {% if usedio.name != "" %}
        <form action="{% url 'saveState' usedio.id %}" method="post">
        {%  csrf_token %}
            <div class="used_io_switches">
                <label for="IO_Name:{{ usedio.id }}">System Name:</label>
                <strong id="IO_Name:{{ usedio.id }}">{{ usedio.name }} </strong>
            <div class="onoffswitch">
                <input type="checkbox" name="io_switch" id="io_active:{{ usedio.id }}" class="onoffswitch-checkbox"
                         onchange="this.form.submit()" {% if usedio.active is True %} checked {% endif %}
                {% if usedio.connectedSystem.connected is False %} disabled{% endif %}>
                <label class="onoffswitch-label" for="io_active:{{ usedio.id }}">
                    <span class="onoffswitch-inner"></span>
                    <span class="onoffswitch-switch"></span>
                </label>
            </div>
            </div>
        </form>
    {% endif %}

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
{% load pwa %}
{% load static %}
<head>
    {% progressive_web_app_meta %}
</head>

<title>PyLight - Home Automation System</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/slider_switch.css' %}">
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey">

<!-- Top container -->
<div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <span class="w3-bar-item w3-right">PyLight - Home Automation System</span>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href="" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <a href="/showTools/" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i> 
            Übersicht
    </a>
    <a href="/manageTools/" class="w3-bar-item w3-button w3-padding"><i class="fa fa-eye fa-fw"></i> 
        Konfiguration
    </a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  Settings</a>
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">
{% block content %}
{% endblock %}
</div>

<script src ={% static 'js/overlay.js' %}></script>
<script src ={% static 'js/install_banner.js' %}></script>

</body>
</html>

templates/initial.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
{% if connectedSystem_list %}
    <div class="w3-row-padding w3-margin-bottom w3-padding-16">
    {% for connectedSystem in connectedSystem_list|dictsortreversed:"id" %}
        {% if forloop.counter0|divisibleby:2 or forloop.counter0 == 0%}
            {% if forloop.counter0 != 0 %}
            </div>
            {% endif %}
            <div class="w3-row-padding w3-margin-bottom w3-padding-16">
        {% endif %}
            <div class="w3-half">
                <div class="w3-container w3-white w3-padding-16">
                    <div class="w3-left">
                        {% block systemForm %}
                        {% endblock %}
                        {% for usedio in connectedSystem.usedio_set.all|dictsortreversed:"id" %}
                            {% block ioForm %}
                            {% endblock %}
                        {% endfor %}
                    </div>
                <div class="w3-clear"></div>
                </div>
            </div>
    {% endfor %}
    </div>

{% else %}
<p>Keine verbundenen Geräte</p>
{% endif %}
{% endblock %}